name: Integration and Unit Tests

on: [push]

jobs:
  integration-unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: npm install
      - run: npm test
        env:
          CI: true
